import type { ReactNode } from "react";
import type { Contact, Message } from "@/domain/inbox";
import { Avatar, Icon } from "@/components/ui";

export type ThreadIdentity = {
  contact: Pick<Contact, "name" | "initials" | "color" | "photoUrl">;
  senderName: string;
  senderPhotoUrl?: string | null;
};

export function ThreadParticipants({
  contact,
  senderName,
  senderPhotoUrl,
}: ThreadIdentity) {
  return (
    <div className="thread-participants">
      <Avatar
        photoUrl={contact.photoUrl}
        initials={contact.initials}
        color={contact.color}
      />
      <span className="thread-sender-avatar" title={senderName}>
        <Avatar photoUrl={senderPhotoUrl} initials={initials(senderName)} />
      </span>
    </div>
  );
}

export function initials(name: string) {
  return name
    .trim()
    .split(/\s+/)
    .slice(0, 2)
    .map((p) => p[0])
    .join("");
}

/** Shared presentation only: never marks read, loads history, or sends messages. */
export function ThreadMessage({
  message,
  identity,
  timezone,
  showAvatar = true,
  children,
}: {
  message: Message & { deliveryStatus?: "sending" | "unknown" | "sent" };
  identity: ThreadIdentity;
  timezone: string;
  showAvatar?: boolean;
  children?: ReactNode;
}) {
  const outbound = message.direction === "outbound";
  return (
    <div className={`message ${outbound ? "outbound" : ""}`}>
      <div className="message-meta">
        {showAvatar ? (
          <Avatar
            photoUrl={
              outbound ? identity.senderPhotoUrl : identity.contact.photoUrl
            }
            initials={
              outbound
                ? initials(identity.senderName)
                : identity.contact.initials
            }
            color={outbound ? "purple" : identity.contact.color}
          />
        ) : null}
        <span>{outbound ? identity.senderName : identity.contact.name}</span>
        {outbound && message.aiGenerated ? (
          <span
            className="message-ai-badge"
            title="Generated by an AI agent"
            aria-label="Generated by an AI agent"
          >
            <Icon name="spark" />
            AI
          </span>
        ) : null}
        {message.createdAt ? (
          <time dateTime={message.createdAt}>
            {new Date(message.createdAt).toLocaleTimeString("en-GB", {
              hour: "2-digit",
              minute: "2-digit",
              timeZone: timezone,
            })}
          </time>
        ) : null}
      </div>
      <div className="bubble">{message.body}</div>
      {message.deliveryStatus === "sending" ? (
        <div className="message-delivery" role="status">
          <span className="message-spinner" aria-hidden="true" />
          Sending…
        </div>
      ) : message.deliveryStatus === "unknown" ? (
        <div className="message-delivery" role="status">
          Send status unavailable
        </div>
      ) : null}
      {children}
    </div>
  );
}
